[project]
name = "DiscordChatGPTBot"
version = "0.1.0"
description = ""
authors = ["NickBrisebois <email@nick-b.ca>"]
readme = "README.md"
requires-python = ">=3.12"
package-mode = false
dependencies = [
    "openai>=2.14.0",
    "discord.py>=2.6.4",
    "pymicroconf>=0.1.0"
]
